version: '3.8'
services:
  ml-api:
    build: ./ml_module
    ports:
      - "5000:5000"
    restart: unless-stopped
  static-site:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro
    restart: unless-stopped
